; Ceci est un fichier de configuration nommé cours.ini
; Les commentaires commencent par ';'

[section_connexion]
protocole=mysql
serveur=mysql-timojabir.alwaysdata.net
port=3306
bd=timojabir_projet
ut=timojabir
mdp=@kr76Fyu900@